"""add_registros_cosecha

Revision ID: 15b70dabafed
Revises: a3f8c2d1e9b7
Create Date: 2026-05-22 13:08:42.071847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '15b70dabafed'
down_revision: Union[str, None] = 'a3f8c2d1e9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros_cosecha',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('semana', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=True),
    sa.Column('cultivo', sa.Enum('vid', 'chacra', 'ind_pasa', 'alfalfa', 'otro', name='cultivocosecha'), nullable=False),
    sa.Column('variedad', sa.String(length=100), nullable=True),
    sa.Column('n_remito', sa.String(length=50), nullable=True),
    sa.Column('n_ciu', sa.String(length=50), nullable=True),
    sa.Column('destino', sa.Enum('mercado_interno', 'bodega', 'exportacion', 'pasas', 'rama_pasa', 'semilla', 'desc', 'fardo', name='destinocosecha'), nullable=False),
    sa.Column('comprador', sa.String(length=150), nullable=True),
    sa.Column('cuadrilla', sa.String(length=150), nullable=True),
    sa.Column('acarreo', sa.String(length=150), nullable=True),
    sa.Column('vehiculo_patente', sa.String(length=20), nullable=True),
    sa.Column('tipo_envase', sa.Enum('caja', 'bin', 'chasis', 'ficha', 'vin', 'bolsa', 'otro', name='tipoenvase'), nullable=False),
    sa.Column('cantidad_envases', sa.Float(), nullable=True),
    sa.Column('peso_unitario_kg', sa.Float(), nullable=True),
    sa.Column('bruto_kg', sa.Float(), nullable=True),
    sa.Column('tara_kg', sa.Float(), nullable=True),
    sa.Column('kg_total', sa.Float(), nullable=False),
    sa.Column('imagen_remito_url', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_cosecha')
    # ### end Alembic commands ###
