"""agregar tabla valvulas

Revision ID: 1b05e61f9a8c
Revises: 32b5a004492a
Create Date: 2026-08-18 19:20:56.835209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b05e61f9a8c'
down_revision: Union[str, None] = '32b5a004492a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valvulas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=False),
    sa.Column('cabezal', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valvulas')
    # ### end Alembic commands ###
