"""add_referencia_id_to_egresos

Revision ID: 1cac1b6d2e3d
Revises: 1b529f62d678
Create Date: 2026-05-16 23:09:01.583886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1cac1b6d2e3d'
down_revision: Union[str, None] = '1b529f62d678'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egresos', sa.Column('referencia_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('egresos', 'referencia_id')
    # ### end Alembic commands ###
