"""agregar finca a users

Revision ID: 2abdd34eebd2
Revises: 72e95d3b28a8
Create Date: 2026-08-24 18:38:19.471147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2abdd34eebd2'
down_revision: Union[str, None] = '72e95d3b28a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('finca', sa.Enum('los_mimbres', 'media_agua', 'caucete', name='finca'), server_default='media_agua', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'finca')
    # ### end Alembic commands ###
