"""riego fin y duracion_horas nullable para riegos en curso

Revision ID: 32154ec7b8f7
Revises: f8a6e10ed72e
Create Date: 2026-07-16 20:38:46.840729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '32154ec7b8f7'
down_revision: Union[str, None] = 'f8a6e10ed72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registros_riego', 'fin',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('registros_riego', 'duracion_horas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index('ix_registros_riego_en_curso', 'registros_riego', ['cabezal'], unique=False, postgresql_where=sa.text('fin IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_registros_riego_en_curso', table_name='registros_riego', postgresql_where=sa.text('fin IS NULL'))
    op.alter_column('registros_riego', 'duracion_horas',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('registros_riego', 'fin',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
