"""add responsable_id a registros_riego y registros_fitosanitarios

Revision ID: 32b5a004492a
Revises: 602658f74f30
Create Date: 2026-08-12 15:14:01.348508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '32b5a004492a'
down_revision: Union[str, None] = '602658f74f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_fitosanitarios', sa.Column('responsable_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'registros_fitosanitarios', 'trabajadores', ['responsable_id'], ['id'])
    op.add_column('registros_riego', sa.Column('responsable_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'registros_riego', 'trabajadores', ['responsable_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registros_riego', type_='foreignkey')
    op.drop_column('registros_riego', 'responsable_id')
    op.drop_constraint(None, 'registros_fitosanitarios', type_='foreignkey')
    op.drop_column('registros_fitosanitarios', 'responsable_id')
    # ### end Alembic commands ###
