"""agregar plan fitosanitario por temporada

Revision ID: 42a9bcab6a1a
Revises: a34b50939ebd
Create Date: 2026-09-08 11:16:00.933207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '42a9bcab6a1a'
down_revision: Union[str, None] = 'a34b50939ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# variedaduva ya existe (usado por parcelas.variedad) -- create_type=False
# evita el CREATE TYPE duplicado, mismo patron que 9cb9232862b4.
variedaduva = postgresql.ENUM(
    'flame', 'red_globe', 'fiesta', 'bonarda', 'sultanina', 'syrah',
    'aspirant', 'alfalfa', 'otro',
    name='variedaduva', create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planes_fitosanitarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('variedad', variedaduva, nullable=False),
    sa.Column('numero_aplicacion', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.String(length=36), nullable=False),
    sa.Column('objetivo', sa.String(length=200), nullable=False),
    sa.Column('dosis_por_ha', sa.Float(), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planes_fitosanitarios_temporada_variedad', 'planes_fitosanitarios', ['temporada', 'variedad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_planes_fitosanitarios_temporada_variedad', table_name='planes_fitosanitarios')
    op.drop_table('planes_fitosanitarios')
    # ### end Alembic commands ###
