"""ordenes_aplicacion

Revision ID: 478138a22e4d
Revises: bb4a5683ae00
Create Date: 2026-09-17 20:08:19.857506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '478138a22e4d'
down_revision: Union[str, None] = 'bb4a5683ae00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fotos_registros_fitosanitarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('registro_fitosanitario_id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['registro_fitosanitario_id'], ['registros_fitosanitarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fotos_registros_fitosanitarios_registro', 'fotos_registros_fitosanitarios', ['registro_fitosanitario_id'], unique=False)
    op.create_table('ordenes_aplicacion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('origen', sa.Enum('plan', 'extra', name='origenordenaplicacion'), nullable=False),
    sa.Column('plan_fitosanitario_id', sa.String(length=36), nullable=True),
    sa.Column('variedad', postgresql.ENUM('flame', 'red_globe', 'fiesta', 'bonarda', 'sultanina', 'syrah', 'aspirant', 'alfalfa', 'otro', name='variedaduva', create_type=False), nullable=False),
    sa.Column('insumo_id', sa.String(length=36), nullable=False),
    sa.Column('dosis_por_ha', sa.Float(), nullable=False),
    sa.Column('objetivo', sa.String(length=200), nullable=False),
    sa.Column('dias_carencia', sa.Integer(), nullable=False),
    sa.Column('dias_reingreso', sa.Integer(), nullable=False),
    sa.Column('fecha_planificada', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'en_curso', 'completada', name='estadoordenaplicacion'), server_default='pendiente', nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['plan_fitosanitario_id'], ['planes_fitosanitarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ordenes_aplicacion_temporada_estado', 'ordenes_aplicacion', ['temporada', 'estado'], unique=False)
    op.create_table('ordenes_aplicacion_parcelas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('orden_id', sa.String(length=36), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'aplicada', name='estadoordenaplicacionparcela'), server_default='pendiente', nullable=False),
    sa.Column('registro_fitosanitario_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['orden_id'], ['ordenes_aplicacion.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.ForeignKeyConstraint(['registro_fitosanitario_id'], ['registros_fitosanitarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ordenes_aplicacion_parcelas_orden', 'ordenes_aplicacion_parcelas', ['orden_id'], unique=False)
    op.create_index('ix_ordenes_aplicacion_parcelas_parcela', 'ordenes_aplicacion_parcelas', ['parcela_id'], unique=False)
    op.create_index('uq_ordenes_aplicacion_parcelas_orden_parcela', 'ordenes_aplicacion_parcelas', ['orden_id', 'parcela_id'], unique=True)
    op.create_index('uq_ordenes_aplicacion_parcelas_registro', 'ordenes_aplicacion_parcelas', ['registro_fitosanitario_id'], unique=True, postgresql_where=sa.text('registro_fitosanitario_id IS NOT NULL'))
    op.add_column('registros_fitosanitarios', sa.Column('observaciones', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('trabajador_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'users', ['trabajador_id'])
    op.create_foreign_key(None, 'users', 'trabajadores', ['trabajador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'trabajador_id')
    op.drop_column('registros_fitosanitarios', 'observaciones')
    op.drop_index('uq_ordenes_aplicacion_parcelas_registro', table_name='ordenes_aplicacion_parcelas', postgresql_where=sa.text('registro_fitosanitario_id IS NOT NULL'))
    op.drop_index('uq_ordenes_aplicacion_parcelas_orden_parcela', table_name='ordenes_aplicacion_parcelas')
    op.drop_index('ix_ordenes_aplicacion_parcelas_parcela', table_name='ordenes_aplicacion_parcelas')
    op.drop_index('ix_ordenes_aplicacion_parcelas_orden', table_name='ordenes_aplicacion_parcelas')
    op.drop_table('ordenes_aplicacion_parcelas')
    op.drop_index('ix_ordenes_aplicacion_temporada_estado', table_name='ordenes_aplicacion')
    op.drop_table('ordenes_aplicacion')
    op.drop_index('ix_fotos_registros_fitosanitarios_registro', table_name='fotos_registros_fitosanitarios')
    op.drop_table('fotos_registros_fitosanitarios')
    # ### end Alembic commands ###
