"""agregar finca a parcelas

Revision ID: 4b4b700b2788
Revises: b9071c06d20c
Create Date: 2026-09-02 22:38:35.814301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4b4b700b2788'
down_revision: Union[str, None] = 'b9071c06d20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcelas', sa.Column('finca', sa.Enum('los_mimbres', 'media_agua', 'caucete', name='finca'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcelas', 'finca')
    # ### end Alembic commands ###
