"""agregar maestro de precios por tarea

Revision ID: 4f80a5fae5f6
Revises: 413793cedac4
Create Date: 2026-08-25 14:25:35.574735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '4f80a5fae5f6'
down_revision: Union[str, None] = '413793cedac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('precios_tarea',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('tarea', sa.String(length=100), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=True),
    sa.Column('unidad_medida', postgresql.ENUM('dias', 'plantas', 'melgas', 'metros', 'vines', 'cajas', 'gamelas', 'otros', name='unidadmedida', create_type=False), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_precios_tarea_temporada', 'precios_tarea', ['temporada'], unique=False)
    op.create_index('uq_precios_tarea_especifico', 'precios_tarea', ['temporada', 'tarea', 'parcela_id', 'unidad_medida'], unique=True, postgresql_where=sa.text('parcela_id IS NOT NULL'))
    op.create_index('uq_precios_tarea_general', 'precios_tarea', ['temporada', 'tarea', 'unidad_medida'], unique=True, postgresql_where=sa.text('parcela_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_precios_tarea_general', table_name='precios_tarea', postgresql_where=sa.text('parcela_id IS NULL'))
    op.drop_index('uq_precios_tarea_especifico', table_name='precios_tarea', postgresql_where=sa.text('parcela_id IS NOT NULL'))
    op.drop_index('ix_precios_tarea_temporada', table_name='precios_tarea')
    op.drop_table('precios_tarea')
    # ### end Alembic commands ###
