"""add fuente to ingresos

Revision ID: 5f262505db41
Revises: b2a72f75457f
Create Date: 2026-08-12 10:55:55.485715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f262505db41'
down_revision: Union[str, None] = 'b2a72f75457f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default backfills existing rows (production already has data);
    # dropped right after so future inserts rely on the ORM-side default only,
    # matching the model (Egreso.fuente uses the same "manual" convention).
    op.add_column(
        'ingresos',
        sa.Column('fuente', sa.String(length=50), nullable=False, server_default='manual'),
    )
    op.alter_column('ingresos', 'fuente', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingresos', 'fuente')
    # ### end Alembic commands ###
