"""add idempotency_key to produccion models

Revision ID: 6605bdca4963
Revises: 9cb9232862b4
Create Date: 2026-07-29 19:07:10.217682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6605bdca4963'
down_revision: Union[str, None] = '9cb9232862b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registros_cosecha', sa.Column('idempotency_key', sa.String(length=36), nullable=True))
    op.create_index('uq_registros_cosecha_idempotency', 'registros_cosecha', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.add_column('registros_fitosanitarios', sa.Column('idempotency_key', sa.String(length=36), nullable=True))
    op.create_index('uq_registros_fitosanitarios_idempotency', 'registros_fitosanitarios', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.add_column('registros_riego', sa.Column('idempotency_key', sa.String(length=36), nullable=True))
    op.create_index('uq_registros_riego_idempotency', 'registros_riego', ['idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.add_column('registros_trabajo', sa.Column('idempotency_key', sa.String(length=36), nullable=True))
    op.create_index('uq_registros_trabajo_idempotency', 'registros_trabajo', ['idempotency_key', 'trabajador_nombre'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_registros_trabajo_idempotency', table_name='registros_trabajo', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_column('registros_trabajo', 'idempotency_key')
    op.drop_index('uq_registros_riego_idempotency', table_name='registros_riego', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_column('registros_riego', 'idempotency_key')
    op.drop_index('uq_registros_fitosanitarios_idempotency', table_name='registros_fitosanitarios', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_column('registros_fitosanitarios', 'idempotency_key')
    op.drop_index('uq_registros_cosecha_idempotency', table_name='registros_cosecha', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_column('registros_cosecha', 'idempotency_key')
    # ### end Alembic commands ###
