"""add termografo tables

Revision ID: 72e95d3b28a8
Revises: 1b05e61f9a8c
Create Date: 2026-08-19 18:18:33.019919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '72e95d3b28a8'
down_revision: Union[str, None] = '1b05e61f9a8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes_importacion_termografo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('intervalo_seg', sa.Integer(), nullable=False),
    sa.Column('rango_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rango_fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cantidad_filas', sa.Integer(), nullable=False),
    sa.Column('cantidad_nuevas', sa.Integer(), nullable=False),
    sa.Column('cantidad_duplicadas', sa.Integer(), nullable=False),
    sa.Column('importado_por', sa.String(length=36), nullable=False),
    sa.Column('importado_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['importado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lotes_importacion_termografo_device_fecha', 'lotes_importacion_termografo', ['device_id', 'importado_at'], unique=False)
    op.create_table('lecturas_termografo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lote_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=50), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperatura', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('humedad', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_importacion_termografo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_lecturas_termografo_natural_key', 'lecturas_termografo', ['device_id', 'fecha_hora'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_lecturas_termografo_natural_key', table_name='lecturas_termografo')
    op.drop_table('lecturas_termografo')
    op.drop_index('ix_lotes_importacion_termografo_device_fecha', table_name='lotes_importacion_termografo')
    op.drop_table('lotes_importacion_termografo')
    # ### end Alembic commands ###
