"""agregar insumos y stock, renombrar dosis_lt_ha

Revision ID: a34b50939ebd
Revises: c0e767795194
Create Date: 2026-09-08 00:09:13.662259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a34b50939ebd'
down_revision: Union[str, None] = 'c0e767795194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insumos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('unidad', sa.Enum('kg', 'lt', name='unidadinsumo'), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimientos_stock',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('insumo_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('ingreso', 'egreso_aplicacion', 'ajuste', name='tipomovimientostock'), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('registro_fitosanitario_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['registro_fitosanitario_id'], ['registros_fitosanitarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movimientos_stock_insumo_fecha', 'movimientos_stock', ['insumo_id', 'fecha'], unique=False)
    op.create_index('uq_movimientos_stock_registro_fitosanitario', 'movimientos_stock', ['registro_fitosanitario_id'], unique=True, postgresql_where=sa.text('registro_fitosanitario_id IS NOT NULL'))
    # Rename en vez de drop+add (lo que generó autogenerate) para no perder
    # la dosis de los registros históricos.
    op.alter_column('registros_fitosanitarios', 'dosis_lt_ha', new_column_name='dosis_por_ha')
    op.add_column('registros_fitosanitarios', sa.Column('insumo_id', sa.String(length=36), nullable=True))
    op.add_column('registros_fitosanitarios', sa.Column('unidad', sa.Enum('kg', 'lt', name='unidadinsumo'), nullable=True))
    op.add_column('registros_fitosanitarios', sa.Column('cantidad_total', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_foreign_key(None, 'registros_fitosanitarios', 'insumos', ['insumo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registros_fitosanitarios', type_='foreignkey')
    op.drop_column('registros_fitosanitarios', 'cantidad_total')
    op.drop_column('registros_fitosanitarios', 'unidad')
    op.drop_column('registros_fitosanitarios', 'insumo_id')
    op.alter_column('registros_fitosanitarios', 'dosis_por_ha', new_column_name='dosis_lt_ha')
    op.drop_index('uq_movimientos_stock_registro_fitosanitario', table_name='movimientos_stock', postgresql_where=sa.text('registro_fitosanitario_id IS NOT NULL'))
    op.drop_index('ix_movimientos_stock_insumo_fecha', table_name='movimientos_stock')
    op.drop_table('movimientos_stock')
    op.drop_table('insumos')
    # ### end Alembic commands ###
