"""add_performance_indexes

Revision ID: a4244d685964
Revises: 15b70dabafed
Create Date: 2026-06-08 18:47:20.248261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a4244d685964'
down_revision: Union[str, None] = '15b70dabafed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trabajadores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('rol', sa.Enum('obrero', 'tractorista', 'encargado_cuadrilla', 'otro', name='roltrabajador'), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_index('ix_ciclos_campana_anio', 'ciclos_campana', ['anio'], unique=False)
    op.create_index('ix_ciclos_campana_parcela_anio', 'ciclos_campana', ['parcela_id', 'anio'], unique=False)
    op.create_index('ix_egresos_fecha', 'egresos', ['fecha'], unique=False)
    op.create_index('ix_egresos_finca_fecha', 'egresos', ['finca', 'fecha'], unique=False)
    op.create_index('ix_egresos_moneda_fecha', 'egresos', ['moneda', 'fecha'], unique=False)
    op.create_index('ix_ingresos_fecha', 'ingresos', ['fecha'], unique=False)
    op.create_index('ix_ingresos_finca_fecha', 'ingresos', ['finca', 'fecha'], unique=False)
    op.create_index('ix_ingresos_moneda_fecha', 'ingresos', ['moneda', 'fecha'], unique=False)
    op.create_index('ix_registros_cosecha_fecha', 'registros_cosecha', ['fecha'], unique=False)
    op.create_index('ix_registros_cosecha_parcela_temporada', 'registros_cosecha', ['parcela_id', 'temporada'], unique=False)
    op.create_index('ix_registros_cosecha_temporada', 'registros_cosecha', ['temporada'], unique=False)
    op.create_index('ix_registros_fitosanitarios_fecha', 'registros_fitosanitarios', ['fecha'], unique=False)
    op.create_index('ix_registros_fitosanitarios_parcela_fecha', 'registros_fitosanitarios', ['parcela_id', 'fecha'], unique=False)
    op.create_index('ix_registros_riego_fecha', 'registros_riego', ['fecha'], unique=False)
    op.create_index('ix_registros_riego_parcela_fecha', 'registros_riego', ['parcela_id', 'fecha'], unique=False)
    op.add_column('registros_trabajo', sa.Column('trabajador_id', sa.String(length=36), nullable=True))
    op.create_index('ix_registros_trabajo_fecha', 'registros_trabajo', ['fecha'], unique=False)
    op.create_index('ix_registros_trabajo_parcela_fecha', 'registros_trabajo', ['parcela_id', 'fecha'], unique=False)
    op.create_index('ix_registros_trabajo_trabajador_id', 'registros_trabajo', ['trabajador_id'], unique=False)
    op.create_foreign_key(None, 'registros_trabajo', 'trabajadores', ['trabajador_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registros_trabajo', type_='foreignkey')
    op.drop_index('ix_registros_trabajo_trabajador_id', table_name='registros_trabajo')
    op.drop_index('ix_registros_trabajo_parcela_fecha', table_name='registros_trabajo')
    op.drop_index('ix_registros_trabajo_fecha', table_name='registros_trabajo')
    op.drop_column('registros_trabajo', 'trabajador_id')
    op.drop_index('ix_registros_riego_parcela_fecha', table_name='registros_riego')
    op.drop_index('ix_registros_riego_fecha', table_name='registros_riego')
    op.drop_index('ix_registros_fitosanitarios_parcela_fecha', table_name='registros_fitosanitarios')
    op.drop_index('ix_registros_fitosanitarios_fecha', table_name='registros_fitosanitarios')
    op.drop_index('ix_registros_cosecha_temporada', table_name='registros_cosecha')
    op.drop_index('ix_registros_cosecha_parcela_temporada', table_name='registros_cosecha')
    op.drop_index('ix_registros_cosecha_fecha', table_name='registros_cosecha')
    op.drop_index('ix_ingresos_moneda_fecha', table_name='ingresos')
    op.drop_index('ix_ingresos_finca_fecha', table_name='ingresos')
    op.drop_index('ix_ingresos_fecha', table_name='ingresos')
    op.drop_index('ix_egresos_moneda_fecha', table_name='egresos')
    op.drop_index('ix_egresos_finca_fecha', table_name='egresos')
    op.drop_index('ix_egresos_fecha', table_name='egresos')
    op.drop_index('ix_ciclos_campana_parcela_anio', table_name='ciclos_campana')
    op.drop_index('ix_ciclos_campana_anio', table_name='ciclos_campana')
    op.drop_table('trabajadores')
    # ### end Alembic commands ###
