"""add presupuestos and metas_produccion

Revision ID: ac50bb4dc8a9
Revises: b7e2c1a4f9d3
Create Date: 2026-07-06 20:51:17.179210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'ac50bb4dc8a9'
down_revision: Union[str, None] = 'b7e2c1a4f9d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Enum types already created by previous migrations (used by egresos/ingresos).
# create_type=False stops SQLAlchemy from emitting CREATE TYPE again.
tipoegreso = postgresql.ENUM(
    'sueldos_personal', 'produccion', 'inversion', 'insumos_varios',
    'impuestos_servicios', 'financiero', 'materia_prima',
    name='tipoegreso', create_type=False,
)
clasificacionegreso = postgresql.ENUM(
    'gerenciales', 'encargados', 'obreros', 'contador', 'abogado',
    'administrador', 'sueldos_otros', 'fertilizantes', 'agroquimicos',
    'produccion_otros', 'inversion_movilidad', 'inversion_infraestructura',
    'inversion_riego', 'inversion_otros', 'rep_repuestos_vehiculos',
    'rep_repuestos_infraestructura', 'combustibles', 'insumos_otros', 'vep',
    'energia_electrica', 'hidraulica', 'rentas', 'gas', 'internet',
    'servicios_otros', 'creditos_bancarios', 'seguros', 'intereses',
    'financiero_otros', 'compra_uva_fresca', 'compra_pasa',
    'materia_prima_otros',
    name='clasificacionegreso', create_type=False,
)
monedatipo = postgresql.ENUM('ars', 'usd', name='monedatipo', create_type=False)

# The only genuinely new enum in this revision.
conceptopresupuesto = postgresql.ENUM(
    'ingreso', 'egreso', name='conceptopresupuesto', create_type=False,
)


def upgrade() -> None:
    # Create only the new type; checkfirst makes the migration re-runnable
    conceptopresupuesto.create(op.get_bind(), checkfirst=True)

    op.create_table('metas_produccion',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=False),
    sa.Column('kg_plan', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temporada', 'parcela_id', name='uq_metas_temporada_parcela')
    )
    op.create_index('ix_metas_produccion_temporada', 'metas_produccion', ['temporada'], unique=False)
    op.create_table('presupuestos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('temporada', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('concepto', conceptopresupuesto, nullable=False),
    sa.Column('tipo', tipoegreso, nullable=True),
    sa.Column('clasificacion', clasificacionegreso, nullable=True),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moneda', monedatipo, nullable=False),
    sa.Column('notas', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_presupuestos_temporada', 'presupuestos', ['temporada'], unique=False)
    op.create_index('ix_presupuestos_temporada_mes', 'presupuestos', ['temporada', 'mes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_presupuestos_temporada_mes', table_name='presupuestos')
    op.drop_index('ix_presupuestos_temporada', table_name='presupuestos')
    op.drop_table('presupuestos')
    op.drop_index('ix_metas_produccion_temporada', table_name='metas_produccion')
    op.drop_table('metas_produccion')
    # Drop only the enum this revision created; shared enums stay untouched
    conceptopresupuesto.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
