"""avatar y cumpleanos en users

Revision ID: acc1562784fa
Revises: 4f80a5fae5f6
Create Date: 2026-08-26 21:01:54.384244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acc1562784fa'
down_revision: Union[str, None] = '4f80a5fae5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('birth_day', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birth_month', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_birthday_notified_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_birthday_notified_year')
    op.drop_column('users', 'birth_year')
    op.drop_column('users', 'birth_month')
    op.drop_column('users', 'birth_day')
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
