"""add comprobantes arca tables

Revision ID: b2a72f75457f
Revises: e53cf61acb03
Create Date: 2026-08-12 10:55:14.153929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2a72f75457f'
down_revision: Union[str, None] = 'e53cf61acb03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lotes_importacion_arca',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tipo_archivo', sa.Enum('recibido', 'emitido', name='tipoarchivoarca'), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('cantidad_filas', sa.Integer(), nullable=False),
    sa.Column('cantidad_nuevas', sa.Integer(), nullable=False),
    sa.Column('cantidad_duplicadas', sa.Integer(), nullable=False),
    sa.Column('importado_por', sa.String(length=36), nullable=False),
    sa.Column('importado_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['importado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lotes_importacion_arca_tipo_fecha', 'lotes_importacion_arca', ['tipo_archivo', 'importado_at'], unique=False)
    op.create_table('comprobantes_arca_importados',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lote_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_archivo', sa.Enum('recibido', 'emitido', name='tipoarchivoarca'), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('tipo_comprobante', sa.Integer(), nullable=False),
    sa.Column('tipo_comprobante_desc', sa.String(length=100), nullable=False),
    sa.Column('es_nota_credito', sa.Boolean(), nullable=False),
    sa.Column('punto_venta', sa.Integer(), nullable=False),
    sa.Column('numero_desde', sa.Integer(), nullable=False),
    sa.Column('numero_hasta', sa.Integer(), nullable=False),
    sa.Column('cod_autorizacion', sa.String(length=30), nullable=True),
    sa.Column('cuit_contraparte', sa.String(length=20), nullable=False),
    sa.Column('denominacion_contraparte', sa.String(length=200), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imp_neto_gravado_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('imp_no_gravado', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('imp_exentas', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('otros_tributos', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_iva', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('imp_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'clasificado', 'descartado', name='estadocomprobantearca'), nullable=False),
    sa.Column('egreso_id', sa.String(length=36), nullable=True),
    sa.Column('ingreso_id', sa.String(length=36), nullable=True),
    sa.Column('clasificado_por', sa.String(length=36), nullable=True),
    sa.Column('clasificado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clasificado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], ),
    sa.ForeignKeyConstraint(['ingreso_id'], ['ingresos.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes_importacion_arca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comprobantes_arca_estado', 'comprobantes_arca_importados', ['tipo_archivo', 'estado'], unique=False)
    op.create_index('ix_comprobantes_arca_fecha_emision', 'comprobantes_arca_importados', ['fecha_emision'], unique=False)
    op.create_index('uq_comprobantes_arca_natural_key', 'comprobantes_arca_importados', ['tipo_archivo', 'tipo_comprobante', 'punto_venta', 'numero_desde', 'cuit_contraparte'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_comprobantes_arca_natural_key', table_name='comprobantes_arca_importados')
    op.drop_index('ix_comprobantes_arca_fecha_emision', table_name='comprobantes_arca_importados')
    op.drop_index('ix_comprobantes_arca_estado', table_name='comprobantes_arca_importados')
    op.drop_table('comprobantes_arca_importados')
    op.drop_index('ix_lotes_importacion_arca_tipo_fecha', table_name='lotes_importacion_arca')
    op.drop_table('lotes_importacion_arca')
    # ### end Alembic commands ###
