"""agregar tablas fotos_parcela y analisis_calidad

Revision ID: b9071c06d20c
Revises: efb307209422
Create Date: 2026-09-02 15:15:12.420088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b9071c06d20c'
down_revision: Union[str, None] = 'efb307209422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisis_calidad',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('origen', sa.Enum('propio', 'laboratorio', name='origenanalisis'), nullable=False),
    sa.Column('brix', sa.Float(), nullable=True),
    sa.Column('acidez', sa.Float(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('estado_sanitario', sa.Enum('sano', 'con_observaciones', 'rechazado', name='estadosanitarioanalisis'), nullable=True),
    sa.Column('laboratorio_nombre', sa.String(length=150), nullable=True),
    sa.Column('informe_url', sa.String(length=500), nullable=True),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analisis_calidad_parcela_fecha', 'analisis_calidad', ['parcela_id', 'fecha'], unique=False)
    op.create_table('fotos_parcela',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fotos_parcela_parcela_fecha', 'fotos_parcela', ['parcela_id', 'fecha'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fotos_parcela_parcela_fecha', table_name='fotos_parcela')
    op.drop_table('fotos_parcela')
    op.drop_index('ix_analisis_calidad_parcela_fecha', table_name='analisis_calidad')
    op.drop_table('analisis_calidad')
    # ### end Alembic commands ###
