"""cheques emitidos y aviso de fecha de pago

Egresos pagados con cheque/echeque pasan a guardar banco, n_cheque y f_pago
(Fecha de Pago) igual que los ingresos, y el gasto impacta en el flujo en
esa fecha (vw_flujo_mensual_real). aviso_pago_enviado_at en ambas tablas
evita repetir el push de "cheque disponible para cobrar / se debita hoy";
los cheques con Fecha de Pago ya pasada se marcan como avisados para no
mandar notificaciones de todo el histórico el primer día.

Revision ID: bbb383698209
Revises: b7c3e9f1a2d4
Create Date: 2026-09-25 12:41:16.301102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

_IMPUTACION = (
    "(CASE WHEN forma_pago::text IN ('cheque', 'echeque') AND f_pago IS NOT NULL "
    "THEN f_pago ELSE fecha END)"
)


def _temporada(col: str) -> str:
    return (
        f"CASE WHEN EXTRACT(MONTH FROM {col}) >= 5 THEN EXTRACT(YEAR FROM {col})::int "
        f"ELSE EXTRACT(YEAR FROM {col})::int - 1 END"
    )


def _vw_flujo(fecha_egreso: str) -> str:
    return f"""
CREATE OR REPLACE VIEW vw_flujo_mensual_real AS
SELECT
    {_temporada(fecha_egreso)}             AS temporada,
    EXTRACT(MONTH FROM {fecha_egreso})::int AS mes,
    'egreso'                               AS concepto,
    tipo::text                             AS tipo,
    moneda::text                           AS moneda,
    SUM(monto)                             AS monto
FROM egresos
GROUP BY 1, 2, 4, 5
UNION ALL
SELECT
    {_temporada(_IMPUTACION)},
    EXTRACT(MONTH FROM {_IMPUTACION})::int,
    'ingreso',
    NULL::text,
    moneda::text,
    SUM(monto)
FROM ingresos
GROUP BY 1, 2, 5
"""


revision: str = 'bbb383698209'
down_revision: Union[str, None] = 'b7c3e9f1a2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('egresos', sa.Column('banco', sa.String(length=100), nullable=True))
    op.add_column('egresos', sa.Column('n_cheque', sa.String(length=50), nullable=True))
    op.add_column('egresos', sa.Column('f_pago', sa.Date(), nullable=True))
    op.add_column('egresos', sa.Column('aviso_pago_enviado_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ingresos', sa.Column('aviso_pago_enviado_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        "UPDATE ingresos SET aviso_pago_enviado_at = now() "
        "WHERE f_pago IS NOT NULL AND f_pago < CURRENT_DATE"
    )
    op.execute(_vw_flujo(_IMPUTACION))


def downgrade() -> None:
    op.execute(_vw_flujo("fecha"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingresos', 'aviso_pago_enviado_at')
    op.drop_column('egresos', 'aviso_pago_enviado_at')
    op.drop_column('egresos', 'f_pago')
    op.drop_column('egresos', 'n_cheque')
    op.drop_column('egresos', 'banco')
    # ### end Alembic commands ###
