"""agregar tipo_riego y cobertura invierno a parcelas

Revision ID: bf337590c30c
Revises: 4b4b700b2788
Create Date: 2026-09-03 00:04:09.972430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bf337590c30c'
down_revision: Union[str, None] = '4b4b700b2788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


tipo_riego_enum = sa.Enum('goteo', 'manto', name='tiporiego')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: op.add_column() con un Enum nuevo NO emite CREATE TYPE (a
    # diferencia de create_table, que si dispara los eventos DDL del tipo) --
    # hay que crearlo a mano antes de usarlo en la columna.
    tipo_riego_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('parcelas', sa.Column('tipo_riego', tipo_riego_enum, nullable=True))
    op.add_column('parcelas', sa.Column('usa_cobertura_invierno', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('parcelas', sa.Column('especie_cobertura_invierno', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcelas', 'especie_cobertura_invierno')
    op.drop_column('parcelas', 'usa_cobertura_invierno')
    op.drop_column('parcelas', 'tipo_riego')
    tipo_riego_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
