"""agregar tabla enlaces_publicos_trazabilidad

Revision ID: c0e767795194
Revises: bf337590c30c
Create Date: 2026-09-03 11:12:45.728767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c0e767795194'
down_revision: Union[str, None] = 'bf337590c30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enlaces_publicos_trazabilidad',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('desde', sa.Date(), nullable=False),
    sa.Column('hasta', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enlaces_publicos_parcela', 'enlaces_publicos_trazabilidad', ['parcela_id'], unique=False)
    op.create_index(op.f('ix_enlaces_publicos_trazabilidad_token'), 'enlaces_publicos_trazabilidad', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_enlaces_publicos_trazabilidad_token'), table_name='enlaces_publicos_trazabilidad')
    op.drop_index('ix_enlaces_publicos_parcela', table_name='enlaces_publicos_trazabilidad')
    op.drop_table('enlaces_publicos_trazabilidad')
    # ### end Alembic commands ###
