"""add clima_cache table

Revision ID: cfb6c28f988d
Revises: a1f4c8d02e6b
Create Date: 2026-08-10 19:21:45.799379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cfb6c28f988d'
down_revision: Union[str, None] = 'a1f4c8d02e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clima_cache',
    sa.Column('finca', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('finca', 'kind')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clima_cache')
    # ### end Alembic commands ###
