"""add kpi views

Hand-written migration: SQL views cannot be autogenerated. These views are
the single source of truth for every KPI in Cambio 5 — consumed by the
FastAPI /kpis endpoints AND by Power BI (read-only user), so the numbers
can never diverge between the two.

Temporada convention everywhere: month >= May belongs to that year's
campaign (2026 = May 2026 -> April 2027), matching RegistroCosecha.

Revision ID: d4e7b2c9f1a5
Revises: ac50bb4dc8a9
Create Date: 2026-07-06

"""
from typing import Sequence, Union

from alembic import op

revision: str = 'd4e7b2c9f1a5'
down_revision: Union[str, None] = 'ac50bb4dc8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Reusable SQL fragment: campaign season derived from a date column.
_TEMPORADA = (
    "CASE WHEN EXTRACT(MONTH FROM {col}) >= 5 "
    "THEN EXTRACT(YEAR FROM {col})::int "
    "ELSE EXTRACT(YEAR FROM {col})::int - 1 END"
)

VIEWS: dict[str, str] = {
    # ── Real monthly cash flow (ingresos + egresos), aligned to budget grain ──
    "vw_flujo_mensual_real": f"""
        SELECT
            {_TEMPORADA.format(col='fecha')} AS temporada,
            EXTRACT(MONTH FROM fecha)::int   AS mes,
            'egreso'                         AS concepto,
            tipo::text                       AS tipo,
            moneda::text                     AS moneda,
            SUM(monto)                       AS monto
        FROM egresos
        GROUP BY 1, 2, 4, 5
        UNION ALL
        SELECT
            {_TEMPORADA.format(col='fecha')},
            EXTRACT(MONTH FROM fecha)::int,
            'ingreso',
            NULL::text,
            moneda::text,
            SUM(monto)
        FROM ingresos
        GROUP BY 1, 2, 5
    """,
    # ── Budget vs real with absolute and % deviation ──────────────────────────
    # Ingreso budget lines are entered per cliente but compared at concepto
    # level: real income client names rarely match budget labels 1:1.
    "vw_presupuesto_vs_real": """
        WITH presup AS (
            SELECT temporada, mes, concepto::text AS concepto, tipo::text AS tipo,
                   moneda::text AS moneda, SUM(monto) AS monto_presupuesto
            FROM presupuestos
            GROUP BY 1, 2, 3, 4, 5
        )
        SELECT
            COALESCE(p.temporada, r.temporada)      AS temporada,
            COALESCE(p.mes, r.mes)                  AS mes,
            COALESCE(p.concepto, r.concepto)        AS concepto,
            COALESCE(p.tipo, r.tipo)                AS tipo,
            COALESCE(p.moneda, r.moneda)            AS moneda,
            COALESCE(p.monto_presupuesto, 0)        AS monto_presupuesto,
            COALESCE(r.monto, 0)                    AS monto_real,
            COALESCE(r.monto, 0) - COALESCE(p.monto_presupuesto, 0) AS desvio,
            CASE WHEN COALESCE(p.monto_presupuesto, 0) <> 0
                 THEN ROUND((COALESCE(r.monto, 0) - p.monto_presupuesto)
                            / p.monto_presupuesto * 100, 1)
            END                                     AS desvio_pct
        FROM presup p
        FULL OUTER JOIN vw_flujo_mensual_real r
          ON  p.temporada = r.temporada
          AND p.mes       = r.mes
          AND p.concepto  = r.concepto
          AND p.moneda    = r.moneda
          AND p.tipo IS NOT DISTINCT FROM r.tipo
    """,
    # ── Production KPIs per parcela: kg/ha, plan deviation, water efficiency ──
    # Litros are ESTIMATED: 16,000 L/h per valve, n valves parsed from the
    # comma-separated `valvula` field (same rule as RegistroRiego.litros_aplicados).
    "vw_kpi_produccion_parcela": f"""
        WITH cosecha AS (
            SELECT temporada, parcela_id, SUM(kg_total) AS kg_total
            FROM registros_cosecha
            WHERE parcela_id IS NOT NULL
            GROUP BY 1, 2
        ),
        riego AS (
            SELECT
                {_TEMPORADA.format(col='fecha')} AS temporada,
                parcela_id,
                SUM(duracion_horas * 16000 * GREATEST(COALESCE(
                    array_length(string_to_array(NULLIF(valvula, ''), ','), 1), 1), 1)
                ) AS litros
            FROM registros_riego
            GROUP BY 1, 2
        )
        SELECT
            c.temporada,
            p.id              AS parcela_id,
            p.nombre          AS parcela_nombre,
            p.variedad::text  AS variedad,
            p.superficie_ha,
            c.kg_total,
            CASE WHEN p.superficie_ha > 0
                 THEN ROUND((c.kg_total / p.superficie_ha)::numeric, 1)
            END               AS kg_ha,
            m.kg_plan,
            CASE WHEN m.kg_plan > 0
                 THEN ROUND(((c.kg_total - m.kg_plan) / m.kg_plan * 100)::numeric, 1)
            END               AS desvio_plan_pct,
            r.litros          AS litros_riego_estimados,
            CASE WHEN c.kg_total > 0 AND r.litros IS NOT NULL
                 THEN ROUND((r.litros / c.kg_total)::numeric, 1)
            END               AS litros_por_kg
        FROM cosecha c
        JOIN parcelas p ON p.id = c.parcela_id
        LEFT JOIN metas_produccion m
               ON m.parcela_id = c.parcela_id AND m.temporada = c.temporada
        LEFT JOIN riego r
               ON r.parcela_id = c.parcela_id AND r.temporada = c.temporada
    """,
    # ── Production per variedad (weighted, not average of averages) ──────────
    "vw_kpi_produccion_variedad": """
        SELECT
            temporada,
            variedad,
            SUM(kg_total)      AS kg_total,
            SUM(superficie_ha) AS superficie_ha,
            CASE WHEN SUM(superficie_ha) > 0
                 THEN ROUND((SUM(kg_total) / SUM(superficie_ha))::numeric, 1)
            END                AS kg_ha
        FROM vw_kpi_produccion_parcela
        GROUP BY 1, 2
    """,
    # ── Labor cost per month per seasonal classification ──────────────────────
    # Jornales counts only day-based records; piecework (plantas, metros, ...)
    # contributes to monto but not to the jornales headcount.
    "vw_kpi_mo_mensual": f"""
        SELECT
            {_TEMPORADA.format(col='fecha')}  AS temporada,
            EXTRACT(MONTH FROM fecha)::int    AS mes,
            clasificacion::text               AS clasificacion,
            SUM(cantidad) FILTER (WHERE unidad_medida = 'dias') AS jornales,
            SUM(monto_total)                  AS monto
        FROM registros_trabajo
        GROUP BY 1, 2, 3
    """,
    # ── Labor cost per parcela (and per ha) per season ────────────────────────
    "vw_kpi_mo_parcela": f"""
        SELECT
            {_TEMPORADA.format(col='t.fecha')} AS temporada,
            t.parcela_id,
            p.nombre         AS parcela_nombre,
            p.superficie_ha,
            SUM(t.cantidad) FILTER (WHERE t.unidad_medida = 'dias') AS jornales,
            SUM(t.monto_total) AS monto,
            CASE WHEN p.superficie_ha > 0
                 THEN ROUND((SUM(t.monto_total) / p.superficie_ha)::numeric, 0)
            END              AS monto_por_ha
        FROM registros_trabajo t
        JOIN parcelas p ON p.id = t.parcela_id
        GROUP BY 1, 2, 3, 4
    """,
}

# Creation order matters (later views depend on earlier ones); drop in reverse.
_ORDER = [
    "vw_flujo_mensual_real",
    "vw_presupuesto_vs_real",
    "vw_kpi_produccion_parcela",
    "vw_kpi_produccion_variedad",
    "vw_kpi_mo_mensual",
    "vw_kpi_mo_parcela",
]


def upgrade() -> None:
    for name in _ORDER:
        op.execute(f"CREATE OR REPLACE VIEW {name} AS {VIEWS[name]}")


def downgrade() -> None:
    for name in reversed(_ORDER):
        op.execute(f"DROP VIEW IF EXISTS {name}")
