"""initial_schema

Revision ID: dd81fff4c510
Revises: 
Create Date: 2026-05-12 11:43:08.186152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd81fff4c510'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcelas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('parral', 'potrero', 'pasero', 'cabezal', name='tipoparcela'), nullable=False),
    sa.Column('variedad', sa.Enum('flame', 'red_globe', 'fiesta', 'bonarda', 'sultanina', 'syrah', 'aspirant', 'alfalfa', 'otro', name='variedaduva'), nullable=True),
    sa.Column('superficie_ha', sa.Float(), nullable=True),
    sa.Column('cabezal_riego', sa.String(length=20), nullable=True),
    sa.Column('coordenadas', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('admin', 'encargado', 'obrero', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ciclos_campana',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('estado_fenologico', sa.Enum('brotacion', 'floracion', 'cuaje', 'envero', 'madurez', 'cosecha', 'latencia', name='estadofenologico'), nullable=False),
    sa.Column('fecha_estado', sa.Date(), nullable=False),
    sa.Column('rendimiento_kg_ha', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('observaciones', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('egresos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('sueldos_personal', 'produccion', 'inversion', 'insumos_varios', 'impuestos_servicios', 'financiero', 'materia_prima', name='tipoegreso'), nullable=False),
    sa.Column('clasificacion', sa.Enum('gerenciales', 'encargados', 'obreros', 'contador', 'abogado', 'administrador', 'sueldos_otros', 'fertilizantes', 'agroquimicos', 'produccion_otros', 'inversion_movilidad', 'inversion_infraestructura', 'inversion_riego', 'inversion_otros', 'rep_repuestos_vehiculos', 'rep_repuestos_infraestructura', 'combustibles', 'insumos_otros', 'vep', 'energia_electrica', 'hidraulica', 'rentas', 'gas', 'internet', 'servicios_otros', 'creditos_bancarios', 'seguros', 'intereses', 'financiero_otros', 'compra_uva_fresca', 'compra_pasa', 'materia_prima_otros', name='clasificacionegreso'), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('ars', 'usd', name='monedatipo'), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('origen', sa.Enum('oficial', 'no_oficial', name='origenpago'), nullable=False),
    sa.Column('finca', sa.Enum('los_mimbres', 'media_agua', 'caucete', name='finca'), nullable=False),
    sa.Column('forma_pago', sa.Enum('efectivo', 'transferencia', 'cheque', 'credito', name='formapago'), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=True),
    sa.Column('fuente', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingresos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('producto', sa.Enum('uva_fresca', 'pasa', 'mosto', 'otro', name='productoingreso'), nullable=False),
    sa.Column('variedad', sa.Enum('flame', 'red_globe', 'fiesta', 'bonarda', 'sultanina', 'syrah', 'aspirant', 'alfalfa', 'otro', name='variedaduva'), nullable=True),
    sa.Column('kg_totales', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('precio_por_kg', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('moneda', sa.Enum('ars', 'usd', name='monedatipo'), nullable=False),
    sa.Column('tipo_cambio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('origen', sa.Enum('oficial', 'no_oficial', name='origenpago'), nullable=False),
    sa.Column('finca', sa.Enum('los_mimbres', 'media_agua', 'caucete', name='finca'), nullable=False),
    sa.Column('forma_pago', sa.Enum('efectivo', 'transferencia', 'cheque', 'credito', name='formapago'), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_fitosanitarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=False),
    sa.Column('producto_nombre', sa.String(length=200), nullable=False),
    sa.Column('dosis_lt_ha', sa.Float(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('dias_carencia', sa.Integer(), nullable=False),
    sa.Column('dias_reingreso', sa.Integer(), nullable=False),
    sa.Column('fecha_habilitacion_cosecha', sa.Date(), nullable=False),
    sa.Column('fecha_habilitacion_reingreso', sa.Date(), nullable=False),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_riego',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=False),
    sa.Column('cabezal', sa.String(length=20), nullable=False),
    sa.Column('valvula', sa.String(length=20), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duracion_horas', sa.Float(), nullable=False),
    sa.Column('mm_aplicados', sa.Float(), nullable=True),
    sa.Column('fertilizante_nombre', sa.String(length=100), nullable=True),
    sa.Column('fertilizante_dosis_lt_ha', sa.Float(), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_trabajo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=True),
    sa.Column('trabajador_nombre', sa.String(length=100), nullable=False),
    sa.Column('clasificacion', sa.Enum('general', 'verano', 'otono', 'invierno', 'primavera', name='clasificaciontarea'), nullable=False),
    sa.Column('tarea', sa.String(length=100), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unidad_medida', sa.Enum('dias', 'plantas', 'melgas', 'metros', 'vines', 'cajas', 'gamelas', 'otros', name='unidadmedida'), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('detalle', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_trabajo')
    op.drop_table('registros_riego')
    op.drop_table('registros_fitosanitarios')
    op.drop_table('ingresos')
    op.drop_table('egresos')
    op.drop_table('ciclos_campana')
    op.drop_table('users')
    op.drop_table('parcelas')
    # ### end Alembic commands ###
