"""add alertas_descartadas table

Revision ID: e53cf61acb03
Revises: cfb6c28f988d
Create Date: 2026-08-10 20:23:30.043542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e53cf61acb03'
down_revision: Union[str, None] = 'cfb6c28f988d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas_descartadas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alerta_id', sa.String(length=128), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descartada_por', sa.String(length=36), nullable=False),
    sa.Column('descartada_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['descartada_por'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas_descartadas')
    # ### end Alembic commands ###
