"""add whatsapp tables

Revision ID: efb307209422
Revises: acc1562784fa
Create Date: 2026-08-27 13:44:43.544227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'efb307209422'
down_revision: Union[str, None] = 'acc1562784fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telefonos_usuarios_whatsapp',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    op.create_index(op.f('ix_telefonos_usuarios_whatsapp_user_id'), 'telefonos_usuarios_whatsapp', ['user_id'], unique=False)
    op.create_table('mensajes_whatsapp_pendientes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wa_message_id', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('texto_original', sa.String(length=1000), nullable=False),
    sa.Column('monto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('pagado', sa.Boolean(), nullable=False),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('estado', sa.Enum('pendiente', 'clasificado', 'descartado', name='estadomensajewhatsapp'), nullable=False),
    sa.Column('egreso_id', sa.String(length=36), nullable=True),
    sa.Column('clasificado_por', sa.String(length=36), nullable=True),
    sa.Column('clasificado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recibido_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clasificado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['egreso_id'], ['egresos.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wa_message_id')
    )
    op.create_index('ix_mensajes_whatsapp_estado', 'mensajes_whatsapp_pendientes', ['estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mensajes_whatsapp_estado', table_name='mensajes_whatsapp_pendientes')
    op.drop_table('mensajes_whatsapp_pendientes')
    op.drop_index(op.f('ix_telefonos_usuarios_whatsapp_user_id'), table_name='telefonos_usuarios_whatsapp')
    op.drop_table('telefonos_usuarios_whatsapp')
    # ### end Alembic commands ###
