"""Detect and clean up duplicate rows created by mobile submit bugs.

Originally written for the double-tap bug (fixed with a useRef guard in the
wizards, 2026-07-17). Extended 2026-07-23 to also catch duplicates from a
second, unrelated bug: the axios retry interceptor in mobile/lib/api.ts
(added 2026-07-20) was retrying POST requests on any response-less error,
including timeouts where the original POST had already been processed by
the server — producing a second identical row a few seconds later. Both
bugs are now fixed at the source (useRef guard + GET-only retry), this
script is for cleaning up rows created while either bug was live.

This script finds such pairs by grouping rows on their natural business key
and clustering by created_at proximity, then (in --commit mode) keeps the
oldest row of each cluster and deletes the rest.

Usage (from backend venv, which has asyncpg installed):
  cd C:\\claude-projects\\los-lirios
  python scripts\\limpiar_duplicados.py             # DRY RUN (no writes)
  python scripts\\limpiar_duplicados.py --commit    # actually delete

Behaviour:
  - Reads DATABASE_PUBLIC_URL from backend/.env (production Railway DB —
    this cleans up rows created during the live pilot, not local dev data)
  - registros_trabajo: groups by (trabajador_nombre, tarea, parcela_id,
    fecha, cantidad, precio_unitario); within each group, rows are
    clustered by created_at using a DUP_WINDOW_SECONDS chain (a row joins
    the current cluster if it's within the window of the previous row)
  - registros_riego: groups by (cabezal, parcela_id, valvula, inicio, fin,
    responsable), same clustering
  - registros_fitosanitarios: groups by (parcela_id, fecha, producto_nombre,
    dosis_lt_ha, responsable), same clustering
  - registros_cosecha: groups by (parcela_id, fecha, destino, kg_total,
    n_remito), same clustering
  - registros_trabajo duplicates also cascade-delete their linked Egreso
    (fuente='trabajo_diario', referencia_id=<id>, generated by
    _build_egreso_for_trabajo) — mirrors what the real delete_trabajo
    endpoint does, to avoid orphaned egresos (see 2026-07-18 incident)
  - --commit always takes a pg_dump backup into pg_backups/ first and
    refuses to continue if the dump fails or looks too small
"""

from __future__ import annotations

import argparse
import asyncio
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import asyncpg

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
ENV_FILE = ROOT / "backend" / ".env"
BACKUP_DIR = ROOT / "pg_backups"

DUP_WINDOW_SECONDS = 60

TRABAJO_KEY_COLS = ["trabajador_nombre", "tarea", "parcela_id", "fecha", "cantidad", "precio_unitario"]
RIEGO_KEY_COLS = ["cabezal", "parcela_id", "valvula", "inicio", "fin", "responsable"]
FITOSANITARIO_KEY_COLS = ["parcela_id", "fecha", "producto_nombre", "dosis_lt_ha", "responsable"]
COSECHA_KEY_COLS = ["parcela_id", "fecha", "destino", "kg_total", "n_remito"]


def read_env_var(key: str) -> str:
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        if line.strip().startswith(f"{key}="):
            return line.split("=", 1)[1].strip().strip('"').strip("'")
    raise RuntimeError(f"{key} not found in {ENV_FILE}")


def asyncpg_url(url: str) -> str:
    # asyncpg.connect wants plain postgresql:// (no SQLAlchemy driver tag)
    return re.sub(r"^postgresql\+\w+://", "postgresql://", url)


def cluster_by_time(rows: list[asyncpg.Record], window_seconds: int) -> list[list[asyncpg.Record]]:
    """rows must already be sorted by created_at. A row joins the current
    cluster if it's within window_seconds of the *previous* row — so a
    burst of 3+ near-simultaneous taps chains into one cluster even if the
    first and last are more than window_seconds apart."""
    clusters: list[list[asyncpg.Record]] = []
    for row in rows:
        if clusters and (row["created_at"] - clusters[-1][-1]["created_at"]).total_seconds() <= window_seconds:
            clusters[-1].append(row)
        else:
            clusters.append([row])
    return [c for c in clusters if len(c) > 1]


async def find_duplicate_groups(
    conn: asyncpg.Connection, table: str, key_cols: list[str],
) -> list[list[asyncpg.Record]]:
    cols = ", ".join(key_cols)
    rows = await conn.fetch(f"SELECT id, created_at, {cols} FROM {table} ORDER BY {cols}, created_at")

    groups: dict[tuple, list[asyncpg.Record]] = {}
    for row in rows:
        key = tuple(row[c] for c in key_cols)
        groups.setdefault(key, []).append(row)

    duplicate_clusters: list[list[asyncpg.Record]] = []
    for group_rows in groups.values():
        group_rows.sort(key=lambda r: r["created_at"])
        duplicate_clusters.extend(cluster_by_time(group_rows, DUP_WINDOW_SECONDS))
    return duplicate_clusters


def print_clusters(table: str, clusters: list[list[asyncpg.Record]]) -> None:
    print(f"\n{table}: {len(clusters)} grupo(s) de duplicados detectados")
    for i, cluster in enumerate(clusters, 1):
        print(f"  Grupo {i} ({len(cluster)} filas, se conserva la más antigua):")
        for row in cluster:
            print(f"    id={row['id']}  created_at={row['created_at'].isoformat()}")


def run_pg_dump_backup(database_public_url: str) -> Path:
    BACKUP_DIR.mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    outfile = BACKUP_DIR / f"los_lirios_prod_{ts}_pre_dedup.dump"
    result = subprocess.run(
        ["pg_dump", "-Fc", database_public_url, "-f", str(outfile)],
        capture_output=True, text=True,
    )
    if result.returncode != 0 or not outfile.exists() or outfile.stat().st_size < 10_000:
        print(result.stderr, file=sys.stderr)
        sys.exit("ERROR: pg_dump falló o el archivo quedó sospechosamente chico — no se borra nada.")
    print(f"\nBackup OK: {outfile} ({outfile.stat().st_size:,} bytes)")
    return outfile


async def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--commit", action="store_true", help="actually delete (default: dry run)")
    args = parser.parse_args()

    database_public_url = read_env_var("DATABASE_PUBLIC_URL")
    conn = await asyncpg.connect(asyncpg_url(database_public_url))
    try:
        trabajo_clusters = await find_duplicate_groups(conn, "registros_trabajo", TRABAJO_KEY_COLS)
        riego_clusters = await find_duplicate_groups(conn, "registros_riego", RIEGO_KEY_COLS)
        fito_clusters = await find_duplicate_groups(conn, "registros_fitosanitarios", FITOSANITARIO_KEY_COLS)
        cosecha_clusters = await find_duplicate_groups(conn, "registros_cosecha", COSECHA_KEY_COLS)

        print_clusters("registros_trabajo", trabajo_clusters)
        print_clusters("registros_riego", riego_clusters)
        print_clusters("registros_fitosanitarios", fito_clusters)
        print_clusters("registros_cosecha", cosecha_clusters)

        n_trabajo = sum(len(c) - 1 for c in trabajo_clusters)
        n_riego = sum(len(c) - 1 for c in riego_clusters)
        n_fito = sum(len(c) - 1 for c in fito_clusters)
        n_cosecha = sum(len(c) - 1 for c in cosecha_clusters)
        print(f"\nTotal filas a borrar si se corre --commit: {n_trabajo} en registros_trabajo, "
              f"{n_riego} en registros_riego, {n_fito} en registros_fitosanitarios, "
              f"{n_cosecha} en registros_cosecha")

        if not args.commit:
            print("\nDRY RUN — nada borrado. Ejecutá con --commit para limpiar.")
            return

        run_pg_dump_backup(database_public_url)

        async with conn.transaction():
            for cluster in trabajo_clusters:
                to_delete = [r["id"] for r in cluster[1:]]  # cluster[0] = created_at más antiguo
                # Cascade-delete the linked Egreso first (mirrors delete_trabajo endpoint) —
                # a raw DELETE on registros_trabajo alone leaves orphaned egresos behind.
                await conn.execute(
                    "DELETE FROM egresos WHERE fuente = 'trabajo_diario' AND referencia_id = ANY($1::text[])",
                    to_delete,
                )
                await conn.execute("DELETE FROM registros_trabajo WHERE id = ANY($1::text[])", to_delete)
            for cluster in riego_clusters:
                to_delete = [r["id"] for r in cluster[1:]]
                await conn.execute("DELETE FROM registros_riego WHERE id = ANY($1::text[])", to_delete)
            for cluster in fito_clusters:
                to_delete = [r["id"] for r in cluster[1:]]
                await conn.execute("DELETE FROM registros_fitosanitarios WHERE id = ANY($1::text[])", to_delete)
            for cluster in cosecha_clusters:
                to_delete = [r["id"] for r in cluster[1:]]
                await conn.execute("DELETE FROM registros_cosecha WHERE id = ANY($1::text[])", to_delete)

        print(f"\nBorrado: {n_trabajo} filas de registros_trabajo, {n_riego} filas de registros_riego, "
              f"{n_fito} filas de registros_fitosanitarios, {n_cosecha} filas de registros_cosecha")
    finally:
        await conn.close()


if __name__ == "__main__":
    asyncio.run(main())
